import{test,expect} from "@playwright/test"

test("sauce lab login ",async({page})=>{
await page.goto("https://www.saucedemo.com/")
const userName = page.getByPlaceholder("Username")
const password = page.getByRole("textbox",{name : "password"})
const login = page.locator("#login-button")
const logo = page.locator('//*[@class = "app_logo"]')
const price = page.locator("(//div[@class='inventory_item_price'])[1]")
const backpack = page.locator("//*[@class='inventory_item'][1]/div[2]/div[2]/div[1]/following-sibling::button[contains(text(),'Add to cart')]")
const cartno = page.locator('//*[@class = "shopping_cart_link"]/span')
const cartpageprice = page.locator("(//div[@class='item_pricebar'])/div")
const first_name = page.locator("(//*[@id='first-name'])")
const last_name = page.locator("(//*[@id='last-name'])")
const pos_code = page.locator("(//*[@id='postal-code'])")
const Continue = page.locator('//*[@id = "continue"]')
const payment_info_value = page.locator('//*[@data-test = "payment-info-value"]')
//checkout 
const checkout = page.getByRole("button",{name:"Checkout"})
const val = await userName.isVisible()
const val1 = await password.isVisible()
await userName.fill("standard_user")
await password.fill("secret_sauce")
await login.click()
const display = await logo.isVisible()
console.log(display)
expect(display).toBeTruthy()
const priceValue = await price.textContent()
console.log(priceValue)
await backpack.click()
const cartvalue = await cartno.textContent()
console.log(cartvalue)
await cartno.click()
const cart_page_value = await cartpageprice.textContent()
console.log(cart_page_value)
expect(priceValue).toEqual(cart_page_value)
const checkout_value = await checkout.isVisible()
console.log(checkout_value)
await checkout.click()
const poscode_display = await pos_code.isVisible()
console.log(poscode_display)
await first_name.fill("sankar")
await last_name.fill("sai")
await pos_code.fill("533223")
await Continue.click()
const info_Value = await payment_info_value.textContent()
let invosplit = await info_Value.split(" ")
console.log(invosplit[1])
})